"""
build.py  —  Keel's command-line button (orchestrator).

Point it at a folder of finished, FX-printed stems and it renders a balanced
stereo mix and a loudness-safe master:

    out/<name>_mix.wav      out/<name>_master.wav

Two modes:

  SINGLE  (default) — mix + master ONE folder of stems:
      python build.py --stems "C:\\path\\to\\stems" --out out
      python build.py --stems ./stems --name my_song --lufs -11 --tp -1
      python build.py --stems ./stems --ref "C:\\refs\\commercial_master.wav"

  BATCH — mix + master EVERY immediate subfolder that contains stems:
      python build.py --batch "C:\\path\\to\\album" --out out
    Each subfolder becomes one project named after that folder.

Stage controls (either mode):
      --mix-only        stop after the mix stage
      --master-only     remaster existing out/<name>_mix.wav

Deterministic: same stems + same options -> identical output, every run.
A QC sheet is written to <out>/REPORT.md after every run.
"""
import argparse
import sys
from pathlib import Path

import recipes
import mixer
import mastering


def _resolve_ref(ref):
    """Split a --ref path into (references_dir, filename) for mastering.master,
    which looks a reference up by name inside a directory."""
    if not ref:
        return None, None
    p = Path(ref).expanduser().resolve()
    return p.parent, p.name


def process_one(stems_dir, out_dir, name, *, target_lufs, tp_ceiling, ref,
                do_mix=True, do_master=True, mix_overrides=None,
                master_overrides=None):
    """Mix and/or master one folder of stems. Returns a REPORT.md row dict, or
    None if it was skipped (no stems / no mix to master)."""
    stems_dir = Path(stems_dir)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    mix_wav = out_dir / f"{name}_mix.wav"
    master_wav = out_dir / f"{name}_master.wav"

    print(f"\n=== {name} ===")
    row = {"slug": name, "mix": None, "master": None}

    if do_mix:
        try:
            rep = mixer.mix(stems_dir, recipes.mix_recipe(mix_overrides), mix_wav)
        except FileNotFoundError as e:
            print(f"  [skip] {e}")
            return None
        row["mix"] = rep
        miss = f" (missing: {', '.join(rep['missing'])})" if rep["missing"] else ""
        print(f"  mix    -> {rep['out']}  {rep['seconds']}s "
              f"{rep['peak_dbfs']} dBFS  stems: {', '.join(rep['stems'])}{miss}")

    if do_master:
        if not mix_wav.exists():
            print(f"  [skip master] no mix at {mix_wav}")
            return row if row["mix"] else None
        m_ov = dict(master_overrides or {})
        if target_lufs is not None:
            m_ov["target_lufs"] = target_lufs
        if tp_ceiling is not None:
            m_ov["tp_ceiling_db"] = tp_ceiling
        refs_dir, ref_name = _resolve_ref(ref)
        if ref_name:
            m_ov["reference"] = ref_name
        recipe = recipes.master_recipe(m_ov)
        rep = mastering.master(mix_wav, recipe, master_wav, references_dir=refs_dir)
        row["master"] = rep
        row["target_lufs"] = recipe.get("target_lufs")
        print(f"  master -> {rep['out']}  [{rep['path']}]  "
              f"{rep['lufs']} LUFS  {rep['true_peak_db']} dBTP")

    return row if (row["mix"] or row["master"]) else None


def discover_batch(parent):
    """Immediate subfolders of `parent` that hold at least one stem, each becoming
    a project named after the subfolder."""
    parent = Path(parent)
    jobs = []
    for sub in sorted(p for p in parent.iterdir() if p.is_dir()):
        try:
            mixer.find_stems(sub)
        except FileNotFoundError:
            continue
        jobs.append((sub, sub.name))
    return jobs


def write_report(report, out_dir):
    """One-glance QC sheet: per-project stem balance (pre/post LUFS) + master
    loudness/true-peak vs. target. Written to <out>/REPORT.md."""
    L = ["# Keel — mix / master QC report",
         "",
         "Auto-generated by `build.py`. Per-project stem balance and final "
         "master loudness / true-peak vs. target.",
         ""]
    for row in report:
        L.append(f"## {row['slug']}")
        L.append("")
        m = row.get("mix")
        if m:
            stems = ", ".join(m["stems"]) + (
                f"  (missing: {', '.join(m['missing'])})" if m["missing"] else "")
            L.append(f"- Mix: {m['seconds']}s, bus peak {m['peak_dbfs']} dBFS, "
                     f"stems: {stems}")
            if m.get("balance"):
                L.append("")
                L.append("| stem | files | pre LUFS | gain dB | post LUFS |")
                L.append("|---|---|---|---|---|")
                for b in m["balance"]:
                    L.append(f"| {b['stem']} | {b['files']} | {b['pre_lufs']} "
                             f"| {b['gain_db']} | {b['post_lufs']} |")
                L.append("")
        ms = row.get("master")
        if ms:
            tgt = row.get("target_lufs")
            off = ("" if tgt is None or not isinstance(ms["lufs"], (int, float))
                   else f"  (target {tgt}, off by {round(ms['lufs'] - tgt, 2)} LU)")
            L.append(f"- Master [{ms['path']}]: **{ms['lufs']} LUFS**, "
                     f"**{ms['true_peak_db']} dBTP**{off}")
        L.append("")
    out_path = Path(out_dir) / "REPORT.md"
    out_path.write_text("\n".join(L), encoding="utf-8")
    print(f"  report -> {out_path}")


def main(argv):
    ap = argparse.ArgumentParser(
        prog="build.py",
        description="Keel: automix + automaster a folder of finished stems.")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--stems", metavar="DIR",
                     help="folder of stems to mix+master (single-project mode)")
    src.add_argument("--batch", metavar="DIR",
                     help="parent folder: mix+master every subfolder with stems")
    ap.add_argument("--out", metavar="DIR", default="out",
                    help="output folder (default: out)")
    ap.add_argument("--name", metavar="BASE",
                    help="output basename in single mode "
                         "(default: the stems folder name)")
    ap.add_argument("--lufs", type=float, metavar="LUFS",
                    help="master loudness target (default: -14.0)")
    ap.add_argument("--tp", type=float, metavar="dBTP",
                    help="master true-peak ceiling (default: -1.0)")
    ap.add_argument("--ref", metavar="FILE",
                    help="reference master; if set, Keel matches it (Matchering) "
                         "and --lufs is ignored")
    ap.add_argument("--mix-only", action="store_true", help="stop after the mix")
    ap.add_argument("--master-only", action="store_true",
                    help="remaster existing out/<name>_mix.wav")
    args = ap.parse_args(argv)

    do_mix = not args.master_only
    do_master = not args.mix_only

    if args.batch:
        jobs = discover_batch(args.batch)
        if not jobs:
            print(f"No subfolders with stems found under {args.batch}")
            return
    else:
        stems = Path(args.stems).expanduser().resolve()
        name = args.name or stems.name
        jobs = [(stems, name)]

    report = []
    for stems_dir, name in jobs:
        row = process_one(
            stems_dir, args.out, name,
            target_lufs=args.lufs, tp_ceiling=args.tp, ref=args.ref,
            do_mix=do_mix, do_master=do_master)
        if row:
            report.append(row)

    if report:
        write_report(report, args.out)
    print(f"\nDone. Outputs in {Path(args.out).resolve()}")


if __name__ == "__main__":
    main(sys.argv[1:])
